import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AOSInit } from "@/components/aos-init";

// Import Poppins dan set ke CSS variable
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // sesuaikan kebutuhan
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Wedding Invitation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-poppins antialiased`}>
        <AOSInit />
        {children}
      </body>
    </html>
  );
}
